- name: Install Firewall
  apt:
    name: ufw
  sudo: true
  tags:
    - install
    - security_setup


- name: Disable All Other Incoming Traffic
  ufw: 
    state: enabled 
    direction: incoming 
    policy: deny
  sudo: true
  tags:
    - install
    - security_setup


- name: Allow SSH, HTTP, HTTPS Traffic
  ufw: 
    proto: tcp 
    port: "{{ item }}" 
    rule: allow
  with_items:
    - 22
    - 80
    - 443
  sudo: true
  tags:
    - install
    - security_setup


- name: Disable 'root' User Direct SSH Access
  lineinfile: 
    dest: "/etc/ssh/sshd_config"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
  notify: Restart SSH
  sudo: true
  tags:
    - install
    - security_setup


- name: Disable Password Authentication
  lineinfile: 
    dest: "/etc/ssh/sshd_config"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
  notify: Restart SSH
  sudo: true
  tags:
    - install
    - security_setup



