- name: Install Latest Version of Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  sudo: true
  tags:
    - install
    - install_nginx


- name: Config Nginx Service
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: "644"
  notify:
    - Restart Nginx
  sudo: true
  tags:
    - install
    - install_nginx


- name: Restart Nginx
  service: 
    name: nginx 
    state: restarted
  sudo: true
  tags:
    - restart_service
    - restart_nginx


- name: Stop Nginx
  service: 
    name: nginx 
    state: stopped
  sudo: true
  tags:
    - stop_service
    - stop_nginx


- name: Start Nginx
  service: 
    name: nginx 
    state: started
  sudo: true
  tags:
    - start_service
    - start_nginx





